datasets:
  full_train: "data/full/train/full_train_unfiltered.csv"
  full_test: "data/full/test/full_test_unfiltered.csv"

target: "Log_MP_RATIO"

preprocess:
  - name: "low_variance"
  - name: "high_correlation"

models:
  - name: "ridge"