datasets:
    full_train: "data/full/train/full_train_unfiltered.csv"
    full_test: "data/full/test/full_test_unfiltered.csv"

target: "Log_MP_RATIO"

gan:
    -   size: 1000
    -   atom_count: 9
    -   smiles_column: "SMILES"
    -   descriptors: "default"

preprocess:
    -   name: "low_variance"
    -   name: "high_correlation"

models:
    -   name: "ridge"
    -   name: "lasso"
    -   name: "elasticnet"
    -   name: "random_forest"
    -   name: "catboost"
    -   name: "xgboost"
