datasets:
  - full_train: "../data/full/train/full_train_unfiltered.csv"
  - full_test: "../data/full/test/full_test_unfiltered.csv"

target: "Log_MP_RATIO"

preprocess:
  - name: "low_variance"
  - name: "high_correlation"

models:
  - name: "elasticNet"
    params:
      alpha:
        min: 1e-10
        max: 1e10
      l1_ratio:
        min: 1e-10
        max: 1
  - name: "lasso"
    params:
      alpha:
        min: 1e-10
        max: 1e10
      tol:
        min: 1e-10
        max: 1e-2
      selection:
        - "cyclic"
        - "random"
  - name: "ridge"
    params:
      alpha:
        min: 1e-10
        max: 1e10
      solver:
        - "auto"
        - "svd"
        - "cholesky"
        - "lsqr"
        - "sparse_cg"
        - "sag"
        - "saga"
  - name: "random_forest"
    params:
      n_estimators:
        min: 50
        max: 1000
      max_depth:
        min: 4
        max: 50
      min_samples_split:
        min: 2
        max: 150
      min_samples_leaf:
        min: 1
        max: 60
  - name: "catboost"
    params:
      objective:
        - "RMSE"
        - "MAE"
        - "Poisson"
        - "Quantile"
        - "MAPE"
      learning_rate:
        min: 1e-10
        max: 1
      colsample_bylevel:
        min: 0.01
        max: 0.1
      max_depth:
        min: 1
        max: 15
      boosting_type:
        - "Ordered"
        - "Plain"
      boostrap_type:
        - "Bayesian"
        - "Bernoulli"
        - "MVS"
  - name: "xgboost"
    params:
      max_depth:
        min: 1
        max: 15
      learning_rate:
        min: 1e-2
        max: 1
      n_estimators:
        min: 50
        max: 1000
      min_child_weight:
        min: 1
        max: 10
      gamma:
        min: 0.01
        max: 1
      subsample:
        min: 0.01
        max: 1
      colsample_bytree:
        min: 0.01
        max: 1
      reg_alpha:
        min: 0.01
        max: 1
      reg_lambda:
        min: 0.01
        max: 1

gan:
  name: "QsarGan"
  data:
    train: "../data/full/train/full_train_unfiltered.csv"
    test: "../data/full/test/full_test_unfiltered.csv"
    tox21: True
    lipo: True
  params:
    learning_rate:
      initial_rate: 0.001
      decay_rate: 0.90
      decay_steps: 5000
    featurizer: "QsarGanFeaturizer"
    edges: 5
    nodes: 5
    embedding_dim: 10
    dropout: 0